### ISSUE TITLE
Un-undoable strokes in eyedraw

### ISSUE THREAD

**Issue by andyqhan** [pomonahci/EyeWrite#15]
We've had this bug for a while, and it's not as bad as it was. However, it still exists. One way to reproduce it:
1. Open eyedraw on two computers.
2. Draw *at the same exact time* on both computers.
3. Repeat 2 until you notice that one of the computers' stroke does not stop when you lift the mouse button. That is, the stroke keeps drawing as if you were click-and-dragging, but you're just dragging.

Then that last stroke on the offending computer is un-undoable.

(The bug persists after closing #13.)

**Comment by andyqhan** [comment]
Additionally, it seems like the combination of the ability to undo the clear-canvas and the ability to redo that undo causes sync problems. I can't pin down a consistent reproduction. Maybe because clear-canvas allows a user to modify other users' strokes. Do we really need redo and clear canvas? (Do we even need undo?)

**Comment by alexpapster** [comment]
As long as erase stroke is available, I think we can remove undo/redo and
be done with this bug.

**Comment by andyqhan** [comment]
Closed with 3f60f87a266bb4b12bcc8871076d6408af2424d5
